name: BRUFEED
favicon: null
layout_spectrum: 0.62838
typography_spectrum: 0.58012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#422c1d'
    - '#ba8660'
    - '#e8d3a2'
    - '#a23d3b'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.7025158575270325
  saturation: 0.6875
  rhythmicContrast: 0.22925033466890454
purpose: []
