name: BRüFEED
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: '¡¡NEW SITE!!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f202a'
    - '#d6d8d7'
    - '#ad190f'
    - '#e88f0d'
    - '#5e6b73'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
