name: BRUFEED
favicon: null
layout_spectrum: 0.14768
typography_spectrum: 0.58012
title: BRUFEED - Award Winning Brütography Collective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#422c1d'
    - '#ba8660'
    - '#e8d3a2'
    - '#a23d3b'
    - '#000000'
  brandStrength: 0
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
