name: BRüFEED
favicon: null
layout_spectrum: 0.21332
typography_spectrum: 0.58012
title: '¡¡NEW SITE!!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#422c1d'
    - '#ba8660'
    - '#e8d3a2'
    - '#a23d3b'
    - '#000000'
  brandStrength: 1
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
